//! Live journey proof against the running Agent Mail daemon.
//!
//! The tests that require the daemon are `#[ignore]`d so a default
//! `cargo test -p agent-mail-native` stays hermetic and cannot be broken by a
//! sibling agent restarting the service mid-run. Run them explicitly:
//!
//! ```text
//! cargo test -p agent-mail-native -- --ignored --nocapture
//! ```
//!
//! Everything here fails LOUDLY rather than skipping. A live test that
//! silently passes when it reached nothing is the vacuous-green pathology
//! these tests exist to disprove: an unreachable daemon, a missing credential,
//! and an empty tool catalogue are all assertion failures, never quiet
//! successes.

use agent_mail_native::journey::{
    self, AgentName, InboxRequest, ProjectKey, ResumePoint, SendRequest,
};
use agent_mail_native::{CursorQuery, DeliveryCursor, Endpoint, MailClient, MailError};
use asupersync::Cx;
use asupersync::runtime::RuntimeBuilder;
use std::future::Future;
use std::time::Duration;

/// The project key this repository registers under.
///
/// Derived from the manifest directory rather than hardcoded, so the test
/// works on any checkout: Agent Mail keys projects by absolute repo path, and
/// `CARGO_MANIFEST_DIR` is `<repo>/crates/agent-mail-native`.
fn project_key() -> String {
    let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(std::path::Path::parent)
        .expect("manifest dir must sit two levels below the repo root")
        .to_string_lossy()
        .into_owned()
}

/// This agent's Agent Mail identity, generated by the daemon on registration
/// (descriptive names are refused with `INVALID_AGENT_NAME`).
const ME: &str = "BrightGorge";

/// Drive an async body on a current-thread runtime, matching the pattern used
/// by `subprocess-contract`'s own tests.
fn run<F>(body: F)
where
    F: Future<Output = ()>,
{
    let runtime = RuntimeBuilder::current_thread()
        .build()
        .expect("runtime must build");
    runtime.block_on(async {
        let _cx = Cx::current().expect("runtime installs a Cx");
        body.await;
    });
}

fn project() -> ProjectKey {
    ProjectKey::new(project_key())
}

fn me() -> AgentName {
    AgentName::new(ME)
}

/// A client pointed at the real daemon, with a discovered credential.
fn live_client() -> MailClient {
    let endpoint = Endpoint::discover();
    assert!(
        endpoint.token().is_some(),
        "no bearer token discoverable; searched {:?}. \
         Export {} or run where an MCP client config exists.",
        Endpoint::discovery_sources(),
        agent_mail_native::endpoint::ENV_PRIMARY_TOKEN
    );
    MailClient::new(endpoint).with_request_timeout(Duration::from_secs(20))
}

#[test]
#[ignore = "requires the live Agent Mail daemon"]
fn daemon_health_is_ready_and_non_empty() {
    run(async {
        let cx = Cx::current().expect("cx");
        let client = live_client();
        let health = client
            .health(&cx)
            .await
            .expect("the daemon must answer /health");

        assert!(health.is_ready(), "daemon not ready: {health:?}");
        // Anti-vacuity: a daemon reporting zero messages and zero projects
        // would make every downstream read trivially empty.
        let messages = health.message_count.unwrap_or(0);
        let projects = health.project_count.unwrap_or(0);
        assert!(messages > 0, "daemon reports an empty store: {health:?}");
        assert!(projects > 0, "daemon reports no projects: {health:?}");
        println!(
            "health: status={} version={:?} projects={projects} messages={messages}",
            health.status, health.version
        );
    });
}

#[test]
#[ignore = "requires the live Agent Mail daemon"]
fn tool_enumeration_is_non_empty_and_covers_the_journey() {
    run(async {
        let cx = Cx::current().expect("cx");
        let client = live_client();
        let tools = client
            .list_tools(&cx)
            .await
            .expect("tools/list must succeed");

        // ANTI-VACUITY: this is the assertion that makes the enumeration
        // meaningful. `list_tools` already refuses an empty catalogue with
        // `EmptyCatalogue`, so a "0 endpoints reachable" pass is impossible.
        assert!(
            !tools.is_empty(),
            "an empty endpoint enumeration is a FAILURE, not a pass"
        );

        // Every operation the dispatch/ack/comms journey depends on must be
        // present. If the daemon drops one, this test names which.
        for required in [
            "register_agent",
            "whois",
            "list_agents",
            "send_message",
            "reply_message",
            "fetch_inbox",
            "fetch_inbox_events",
            "acknowledge_message",
            "get_message_delivery_receipt",
            "file_reservation_paths",
            "renew_file_reservations",
            "release_file_reservations",
            "check_file_reservation_conflicts",
        ] {
            assert!(
                tools.iter().any(|name| name == required),
                "daemon does not advertise `{required}`; it has {} tools: {tools:?}",
                tools.len()
            );
        }
        println!("tools advertised: {}", tools.len());
    });
}

/// The full journey: send to self, read back, acknowledge, and prove the
/// delivery cursor advanced across two reads with no replay and no gap.
#[test]
#[ignore = "requires the live Agent Mail daemon"]
fn round_trip_send_read_ack_and_cursor_advances_without_replay_or_gap() {
    run(async {
        let cx = Cx::current().expect("cx");
        let client = live_client();
        let project = project();
        let me = me();

        // ---- 1. Baseline the durable cursor WITHOUT consuming backlog. ----
        let baseline_page = journey::fetch_inbox_events(
            &cx,
            &client,
            &project,
            &me,
            CursorQuery::PositionNow,
            None,
        )
        .await
        .expect("position_now must succeed");
        assert!(
            baseline_page.events.is_empty(),
            "position_now must return NO events, got {}",
            baseline_page.events.len()
        );
        let baseline = ResumePoint::after_processing(&project, &me, &baseline_page);
        println!("baseline cursor: {}", baseline.cursor());

        // ---- 2. Send a message to ourselves. ----
        let marker = format!(
            "agent-mail-native round-trip {}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .expect("clock")
                .as_millis()
        );
        let receipt = journey::send(
            &cx,
            &client,
            &SendRequest::new(
                project.clone(),
                me.clone(),
                vec![me.clone()],
                marker.clone(),
                format!(
                    "Live round-trip proof for crates/agent-mail-native.\n\n\
                     FROM: BrightGorge (AmNative)\nREPLY VIA: Agent Mail \
                     send_message to BrightGorge, project {}\n\n\
                     marker: {marker}",
                    project.as_str()
                ),
            ),
        )
        .await
        .expect("send_message must succeed");

        let message_id = receipt
            .message_id()
            .expect("a delivered copy must carry an id");
        assert_eq!(receipt.count, 1, "expected exactly one delivery");
        println!(
            "sent {message_id} (verified_sender={})",
            receipt.verified_sender
        );

        // ---- 3. Read the new event by resuming from the baseline. ----
        // `resume_from` also proves continuity: it refuses if the baseline has
        // fallen below the recipient's retained floor.
        let first_read = journey::resume_from(&cx, &client, &baseline, None)
            .await
            .expect("resume from baseline must succeed");

        assert!(
            !first_read.events.is_empty(),
            "the message we just sent produced no delivery event"
        );
        let ours = first_read
            .events
            .iter()
            .find(|event| event.message_id == message_id)
            .expect("our own message must appear in the page (NO GAP)");
        println!(
            "first read: {} event(s), ours at {} (message {})",
            first_read.events.len(),
            ours.cursor,
            ours.message_id
        );

        // The cursor MUST have advanced past the baseline.
        assert!(
            first_read
                .next_cursor
                .advanced_beyond(baseline.cursor()),
            "cursor did not advance: baseline {} -> next {}",
            baseline.cursor(),
            first_read.next_cursor
        );
        // And the event's own position must lie strictly after the baseline,
        // which is what "no gap" means for the page we were handed.
        assert!(
            ours.cursor.advanced_beyond(baseline.cursor()),
            "our event at {} is not after the baseline {}",
            ours.cursor,
            baseline.cursor()
        );

        // ---- 4. Read again from the NEW cursor: no replay. ----
        let after_first = ResumePoint::after_processing(&project, &me, &first_read);
        let second_read = journey::resume_from(&cx, &client, &after_first, None)
            .await
            .expect("second resume must succeed");

        assert!(
            !second_read
                .events
                .iter()
                .any(|event| event.message_id == message_id),
            "NO REPLAY violated: message {message_id} was returned twice"
        );
        assert!(
            second_read
                .events
                .iter()
                .all(|event| event.cursor.advanced_beyond(after_first.cursor())),
            "second read returned an event at or below the persisted cursor"
        );
        println!(
            "second read: {} event(s), next {} (no replay)",
            second_read.events.len(),
            second_read.next_cursor
        );

        // ---- 5. Read the inbox and find our message unread. ----
        let inbox = journey::fetch_inbox(
            &cx,
            &client,
            &InboxRequest {
                limit: Some(25),
                ..InboxRequest::read_only(project.clone(), me.clone())
            },
        )
        .await
        .expect("fetch_inbox must succeed");

        let stored = inbox
            .iter()
            .find(|message| message.id == message_id)
            .expect("our message must be in the inbox");
        assert!(
            stored.ack_required,
            "the message was sent ack_required; the store disagrees"
        );

        // A non-mutating read must NOT have set read_ts.
        assert!(
            stored.is_unread(),
            "mark_read=false still consumed the unread state (read_ts={:?})",
            stored.read_ts
        );

        // Reconciliation must therefore surface it as owed work.
        let owed = journey::reconcile(&first_read.events, &inbox);
        assert!(
            owed.iter().any(|item| item.message_id == message_id),
            "an unread delivered message must reconcile as outstanding"
        );

        // ---- 6. Acknowledge, and confirm the daemon recorded it. ----
        let ack = journey::acknowledge(&cx, &client, &project, &me, message_id)
            .await
            .expect("acknowledge must succeed");
        assert_eq!(ack.message_id, message_id);
        assert!(ack.acknowledged, "daemon did not record the ack: {ack:?}");
        println!("acked {message_id} at {:?}", ack.acknowledged_at);

        // ---- 7. The durable receipt separates persisted from signalled. ----
        let delivery = journey::delivery_receipt(&cx, &client, &project, message_id)
            .await
            .expect("delivery receipt must succeed");
        assert!(delivery.persisted, "message not persisted: {delivery:?}");
        let recipient = delivery
            .recipients
            .iter()
            .find(|entry| entry.recipient == ME)
            .expect("we must appear as a recipient");
        assert!(
            recipient.acknowledged,
            "receipt disagrees with the ack we just made: {recipient:?}"
        );
        println!(
            "receipt: persisted={} signaled={} acknowledged={}",
            recipient.persisted, recipient.signaled, recipient.acknowledged
        );
    });
}

/// The daemon and the CLI are independent readers over one store.
#[test]
#[ignore = "requires the live Agent Mail daemon and the am CLI"]
fn daemon_and_cli_oracle_agree_on_the_tail() {
    run(async {
        let cx = Cx::current().expect("cx");
        let client = live_client();
        let project = project();
        let me = me();

        let daemon_page = journey::fetch_inbox_events(
            &cx,
            &client,
            &project,
            &me,
            CursorQuery::PositionNow,
            None,
        )
        .await
        .expect("daemon read must succeed");

        let cli = agent_mail_native::oracle::cli_position_now(&cx, &project, &me)
            .await
            .expect("CLI oracle read must succeed");

        let agreement = agent_mail_native::oracle::compare(&daemon_page, &cli);
        println!(
            "daemon tail {} vs CLI tail {} (skew {})",
            daemon_page.tail_cursor,
            cli.tail_cursor,
            agreement.skew()
        );
        // The log is append-only and live, so the CLI may be slightly AHEAD if
        // mail landed between the two reads. It must never be BEHIND.
        assert!(
            agreement.skew() >= 0,
            "the CLI read BEHIND the daemon, which append-only cannot explain: {agreement:?}"
        );
    });
}

/// A dead port must produce `Unreachable`, never an empty result.
///
/// This is the typed-refusal proof, and it runs WITHOUT the daemon: the whole
/// point is that "nothing listening" and "nothing in the mailbox" are
/// different answers.
#[test]
fn a_dead_port_is_unreachable_not_an_empty_inbox() {
    run(async {
        let cx = Cx::current().expect("cx");

        // Reserve a port, then release it, so nothing is listening on it.
        let listener =
            std::net::TcpListener::bind("127.0.0.1:0").expect("bind an ephemeral port");
        let port = listener.local_addr().expect("local addr").port();
        drop(listener);

        // A token is supplied deliberately: without one the client would
        // refuse with `MissingCredential` before any I/O, and this test would
        // prove nothing about reachability.
        let endpoint = Endpoint::new(
            format!("http://127.0.0.1:{port}/mcp/"),
            Some("not-a-real-token".to_owned()),
        );
        let client = MailClient::new(endpoint).with_request_timeout(Duration::from_secs(5));

        let outcome = journey::fetch_inbox_events(
            &cx,
            &client,
            &project(),
            &me(),
            CursorQuery::PositionNow,
            None,
        )
        .await;

        match outcome {
            Err(MailError::Unreachable { endpoint, detail }) => {
                assert!(
                    endpoint.contains(&port.to_string()),
                    "the refusal must name the endpoint: {endpoint}"
                );
                println!("dead port refused correctly: {endpoint} ({detail})");
            }
            Err(other) => panic!(
                "a dead port must be Unreachable, not {other} \
                 (a different variant hides the transport failure)"
            ),
            Ok(page) => panic!(
                "a dead port returned SUCCESS with {} events and tail {} — \
                 this is the exact false-negative this crate exists to prevent",
                page.events.len(),
                page.tail_cursor
            ),
        }
    });
}

/// A missing credential is its own refusal, distinct from unreachability.
#[test]
fn a_missing_credential_refuses_before_any_io() {
    run(async {
        let cx = Cx::current().expect("cx");
        // Port 9 (discard) with NO token: the credential check must fire
        // first, proving we never attempted the connection.
        let client = MailClient::new(Endpoint::new("http://127.0.0.1:9/mcp/", None));

        match journey::list_agents(&cx, &client, &project()).await {
            Err(MailError::MissingCredential { searched }) => {
                assert!(
                    !searched.is_empty(),
                    "the refusal must name where a token was looked for"
                );
            }
            Err(other) => panic!("expected MissingCredential, got {other}"),
            Ok(agents) => panic!("expected a refusal, got {} agents", agents.len()),
        }
    });
}

#[test]
#[ignore = "requires the live Agent Mail daemon"]
fn first_resume_from_origin_succeeds_for_recipient_with_later_first_event() {
    run(async {
        let cx = Cx::current().expect("runtime installs a Cx");
        let endpoint = Endpoint::discover();
        if endpoint.token().is_none() {
            panic!(
                "K0_LIVE_UNAVAILABLE: no Agent Mail credential; searched {:?}",
                Endpoint::discovery_sources()
            );
        }
        let client = MailClient::new(endpoint).with_request_timeout(Duration::from_secs(20));
        let from = ResumePoint::restored(project(), me(), DeliveryCursor::ORIGIN);
        let page = match journey::resume_from(&cx, &client, &from, Some(50)).await {
            Ok(page) => page,
            Err(
                unavailable @ (MailError::Unreachable { .. }
                | MailError::Unauthorized { .. }
                | MailError::MissingCredential { .. }),
            ) => panic!("K0_LIVE_UNAVAILABLE: {unavailable:?}"),
            Err(error) => panic!("K0_LIVE_ASSERTION_BROKEN: {error:?}"),
        };
        assert!(
            !page.events.is_empty(),
            "K0_LIVE_EMPTY_PAGE: the live attribution leg reached no events"
        );
        assert!(
            page.events
                .iter()
                .all(|event| event.cursor > DeliveryCursor::ORIGIN),
            "K0_LIVE_ASSERTION_BROKEN: returned event did not advance past origin"
        );
    });
}

/// CENSUS — the leg that makes the `#[ignore]` classification honest instead of
/// a mute. NOT `#[ignore]`d, deliberately: it must run in the sanctioned
/// invocation.
///
/// `#[ignore]` converts a visible red into an invisible hole, and
/// `--include-ignored` has ZERO callers in this repository, so the ignored set
/// is otherwise unguarded — a sixth live leg could arrive with no red anywhere.
/// That is exactly how `first_resume_from_origin_succeeds_for_recipient_with_later_first_event`
/// shipped without the attribute its own module contract (`:3-9`) requires and
/// broke `cargo test -p agent-mail-native` wherever no credential exists.
///
/// Two directions, because a one-directional census is half an instrument:
/// a leg that reaches the daemon MUST be ignored, and a hermetic leg MUST NOT
/// be — an ignored hermetic leg is a passing test nobody runs.
#[test]
fn every_live_leg_is_classified_and_the_live_set_is_pinned() {
    const SOURCE: &str = include_str!("live_journey.rs");
    // Built with `concat!` on purpose: a literal needle would appear in this
    // function's own source and classify the census itself as a live leg.
    const REACHES_DAEMON: [&str; 2] = [concat!("live_", "client()"), concat!("Endpoint::", "discover()")];
    // Pinned BY NAME so a new live leg is a deliberate edit here, never a
    // silent arrival.
    const EXPECTED_LIVE: [&str; 5] = [
        "daemon_health_is_ready_and_non_empty",
        "tool_enumeration_is_non_empty_and_covers_the_journey",
        "round_trip_send_read_ack_and_cursor_advances_without_replay_or_gap",
        "daemon_and_cli_oracle_agree_on_the_tail",
        "first_resume_from_origin_succeeds_for_recipient_with_later_first_event",
    ];

    let blocks: Vec<&str> = SOURCE.split("\n#[test]").skip(1).collect();
    assert!(
        blocks.len() >= EXPECTED_LIVE.len() + 1,
        "census parsed {} #[test] blocks, fewer than the {} live legs it already knows about: \
         the PARSER is broken, not the file — an empty or short scan must never read as a pass",
        blocks.len(),
        EXPECTED_LIVE.len()
    );

    let mut live = Vec::new();
    for block in &blocks {
        let name = block
            .lines()
            .find_map(|line| line.strip_prefix("fn "))
            .and_then(|rest| rest.split('(').next())
            .expect("every #[test] block must declare a top-level fn");
        let attributes: String = block
            .lines()
            .take_while(|line| !line.starts_with("fn "))
            .collect::<Vec<_>>()
            .join("\n");
        let ignored = attributes.contains("#[ignore");
        let reaches_daemon = REACHES_DAEMON.iter().any(|needle| block.contains(needle));
        if reaches_daemon {
            live.push(name.to_owned());
            assert!(
                ignored,
                "live leg `{name}` reaches the daemon but carries no #[ignore]: a default \
                 `cargo test -p agent-mail-native` then fails wherever no Agent Mail credential \
                 exists, which is every Contabo worker"
            );
        } else {
            assert!(
                !ignored,
                "hermetic leg `{name}` is #[ignore]d: an ignored leg is not a passing leg, and \
                 --include-ignored has zero callers in this repository"
            );
        }
    }

    assert_eq!(
        live, EXPECTED_LIVE,
        "the live-leg set changed. Pin it deliberately here — an unpinned set is how an \
         unclassified live leg arrives silently"
    );
}
