//! Rust TYPE inventory for the workspace: every public `struct`/`enum` each
//! crate declares, the name collisions between crates, the vocabulary we are
//! missing, and the named zeros. GENERATED by walking `crates/*/src/**/*.rs`
//! — never drawn by hand.
//!
//! GATE SHAPE (bead ipg.17):
//! - Two crates declaring the same public type name FAIL, unless the name
//!   carries a row in [`ALLOWED_COLLISIONS`] with a non-empty reason.
//! - A crate with zero declarations AND zero re-exports FAILS unless it is a
//!   named zero in [`NAMED_ZEROS`].
//! - An inventory that discovered zero types FAILS (anti-vacuity): the scan
//!   set is never allowed to be silently empty.
//! - The missing-vocabulary list is part of the output; an inventory that
//!   lists only what exists cannot show a gap, and the gap is the point.
//!
//! NO-CLAIM: this proves SHAPE, not SEMANTICS. Identically-named types may be
//! legitimately distinct; differently-named types may mean the same thing
//! (the ack/receipt dialect split). The gate catches name collisions; a human
//! decides whether the vocabulary is actually split. Absence is checked by
//! exact name.
//!
//! Upstream evidence for the missing rows was DERIVED from the asupersync
//! source at the pinned rev (fa3c01aec, v0.4.9), not from memory:
//! - `Outcome<T,E>` variants are Ok/Err/Cancelled(CancelReason)/Panicked
//!   (types/outcome.rs:218). There is no `Completed`.
//! - asupersync declares TWO `AckKind`s: the UNINHABITED marker
//!   `pub enum AckKind {}` at obligation/graded.rs:790, and the inhabited
//!   five-variant one at messaging/class.rs:83.
//! - `DeliveryClass` lives at messaging/class.rs:17, behind
//!   `#[cfg(feature = "messaging-fabric")]` (messaging/mod.rs:78-79).
//! - `Budget` lives at types/budget.rs:173 and `asupersync::types` COMPILES
//!   at our pin (verified: `cargo check -p omp-types`), so Budget is
//!   reachable upstream today.
//! - `messaging::class` is NOT reachable: without the feature, E0433
//!   (probe-verified 2026-08-31); with `messaging-fabric` alone, consumer.rs:1299
//!   has an un-gated `fn default()` calling `TaskId::new_ephemeral()` which is
//!   `cfg(any(test, feature = "test-internals"))` -> E0599 (measured by the
//!   orchestrator, 2026-08-31). Enabling test-internals would reintroduce the
//!   leak upstream issue #46 closed. Hence BLOCKED UPSTREAM.

use std::collections::BTreeMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::ProbeState;

/// The kind of a public type declaration.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TypeKind {
    Struct,
    Enum,
}

impl std::fmt::Display for TypeKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TypeKind::Struct => write!(f, "struct"),
            TypeKind::Enum => write!(f, "enum"),
        }
    }
}

/// One public type declaration found in a crate's src tree.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypeDecl {
    pub crate_name: String,
    pub name: String,
    pub kind: TypeKind,
    pub rel_path: String,
    pub line: usize,
    /// True when the declaration sits inside a `#[cfg(test)]` module and is
    /// therefore not part of the crate's public API surface. Test-module
    /// declarations never participate in collision detection.
    pub in_test_module: bool,
}

/// One type a crate PROVIDES via `pub use` re-export rather than declaration
/// (the omp-types vocabulary crate is made entirely of these).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypeReexport {
    pub crate_name: String,
    pub name: String,
    pub from: String,
}

/// The per-crate slice of the inventory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CrateTypes {
    pub crate_name: String,
    pub decls: Vec<TypeDecl>,
    pub reexports: Vec<TypeReexport>,
}

/// A name declared by MORE THAN ONE crate. `allowance` carries the reason
/// when the duplication is a named, accepted row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypeCollision {
    pub name: String,
    pub crates: Vec<String>,
    /// `crate/rel_path:line` for each non-test declaration site.
    pub sites: Vec<String>,
    pub allowance: Option<String>,
}

/// Status of a vocabulary name the ecosystem should own.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MissingStatus {
    /// No crate in this workspace declares it AND upstream does not have it
    /// under this exact name.
    AbsentEverywhere,
    /// Upstream has it at our pin and the module compiles — adoption is a
    /// separate decision; mapping a surface is not adopting it.
    PresentUpstreamUsable,
    /// Upstream has it but the module does not compile / is not reachable at
    /// our pin. A named absence, never a quiet omission.
    PresentUpstreamBlocked,
    /// A local crate declares the name with UNRELATED semantics to the
    /// upstream type of the same name.
    PresentWrongSemantics,
}

/// One row of the missing-vocabulary list.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MissingTypeRow {
    pub name: String,
    pub status: MissingStatus,
    /// Where it would come from, or why it exists nowhere. Carries file:line
    /// evidence, derived from definitions rather than from memory.
    pub evidence: String,
}

/// THE seam decision (bead acceptance 3): the Observation collision gets a
/// DECISION, not an allowance row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SeamDecision {
    pub type_name: String,
    pub decision: String,
    pub shared_home: String,
    pub rationale: String,
    pub migration: Vec<String>,
}

/// Aggregate counts for the inventory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypeCounts {
    pub enums: usize,
    pub structs: usize,
    pub reexports: usize,
    pub crates_scanned: usize,
    pub crates_with_types: usize,
}

/// The full generated inventory.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypeInventory {
    pub schema_version: String,
    pub generated_by: String,
    pub state: ProbeState,
    pub counts: TypeCounts,
    pub crates: Vec<CrateTypes>,
    pub collisions: Vec<TypeCollision>,
    pub missing: Vec<MissingTypeRow>,
    pub seam_decisions: Vec<SeamDecision>,
    pub named_zeros: Vec<String>,
}

/// Named collision allowances: (type name, the exact crate pair, reason).
/// An allowance matches ONLY the named crate set — the same type name
/// colliding between ANY OTHER pair of crates is still REFUSED. Every row
/// must correspond to a real collision (a stale row is an error — same
/// discipline as UNWIRED_LANE_ALLOWANCE).
///
/// NOTE: Observation is deliberately NOT here. It has a DECISION row
/// ([`observation_seam_decision`]), not an allowance — the bead requires the
/// seam to converge, so the gate treats an Observation collision as REFUSED
/// until the convergence lands.
pub const ALLOWED_COLLISIONS: &[(&str, &str, &str)] = &[
    (
        "Finding",
        "finding+state-wildcard-lint",
        "finding::Finding is an issue record for dispatch; \
         state-wildcard-lint::Finding is a lint scan result. Distinct \
         semantics today. Dies when finding-dispatch adopts a shared finding \
         type or when the zero-caller `finding` crate is retired — whichever \
         lands first.",
    ),
    (
        "LintReport",
        "state-wildcard-lint+undrained-pipe-lint",
        "Both report the same SHAPE (findings + scanned count) over \
         different finding types. Dies when a generic LintReport<T> lands in \
         a shared gate-support crate.",
    ),
    (
        "Violation",
        "no-shell-gate+undrained-pipe-lint",
        "no-shell-gate::Violation (extension + path) and \
         undrained-pipe-lint::Violation (pipe-drain site) are unrelated \
         shapes. Dies with a shared Violation trait in a gate-common crate; \
         until then the collision is cosmetic, both are crate-gated at use \
         sites.",
    ),
    (
        "DispatchIntent",
        "ack-spine+dispatch-claim-fence",
        "ack-spine::DispatchIntent is a STRUCT (bead_id/pane_id/session) naming one \
         concrete pane-targeted dispatch for the ledger; dispatch-claim-fence's is an \
         ENUM (Bead/Broadcast/Correction) naming the KIND of dispatch authorized. \
         Different arities, no shared caller. The enum is a kind, not an intent, so \
         the honest resolution is a rename rather than a unification. Dies when \
         omp-types provides the shared dispatch vocabulary.",
    ),
    (
        "GateError",
        "no-shell-gate+porting-gate",
        "no-shell-gate::GateError carries GitFailed and the empty-scan anti-vacuity \
         case for a FILE-EXTENSION scan; porting-gate::GateError carries \
         EmptyCandidates/InvalidCandidate/Io/Metadata for a CRATE-ARRIVAL check. \
         Disjoint domains, no shared caller. Dies when a workspace error trait exists; \
         unifying them earlier would couple two gates sharing only a suffix.",
    ),
];
/// Crates allowed to own zero public types, with the reason each zero is
/// real. `omp-types` is a re-export vocabulary crate: it must have reexports
/// > 0 or it is genuinely empty and the gate fails it.
pub const NAMED_ZEROS: &[(&str, &str)] = &[
    (
        "finding-dispatch",
        "Zero-caller library today (flagged elsewhere); owns no type yet. \
         Named zero, not silence.",
    ),
    (
        "pane-dispatch-fence",
        "Deliberate leaf: admission fence logic over types owned by its \
         callers. Named zero, not silence.",
    ),
    (
        "omp-types",
        "Re-export vocabulary crate (asupersync::types facade). Must carry \
         reexports > 0; zero declarations is its SHAPE, not an absence.",
    ),
];

/// THE DECISION for the Observation seam. This is a decision, not an
/// allowance: the producer's per-pane observation and the consumer's fleet
/// aggregate are two LEVELS of one concept and get one vocabulary in
/// omp-types, so the free_capacity/dispatchable filter divergence that hid a
/// NewlyIdle pane becomes impossible to express without a compile error.
pub fn observation_seam_decision() -> SeamDecision {
    SeamDecision {
        type_name: "Observation".to_owned(),
        decision: "CONVERGE on one shared vocabulary in omp-types".to_owned(),
        shared_home: "omp-types::observe".to_owned(),
        rationale: concat!(
            "tick-monitor::Observation is PER-PANE {pane_id, state, hash, at} ",
            "(tick-monitor/src/lib.rs:489); omp-orchestrator::Observation is a ",
            "FLEET AGGREGATE {panes: Vec<PaneObservation>, queue, gate_census} ",
            "(omp-orchestrator/src/lib.rs:190). Three names, two levels, zero ",
            "shared types across the seam: producer and consumer agree only by ",
            "convention, which is exactly how free_capacity got derived from the ",
            "same filter as dispatchable and a NewlyIdle pane became invisible as ",
            "capacity while every watchdog reported healthy. One shared PaneState ",
            "crossing the seam turns that defect class into a compile error: a ",
            "filter change that breaks the consumer's assumptions no longer ",
            "compiles, because there is one enum and both sides match on it ",
            "exhaustively."
        )
        .to_owned(),
        migration: vec![
            "1. omp-types gains `observe`: PaneObservation (renamed from \
             tick-monitor::Observation, fields intact) and CycleObservation \
             (renamed from omp-orchestrator::Observation, holding \
             Vec<PaneObservation>)."
                .to_owned(),
            "2. tick-monitor re-exports/aliases PaneObservation; its pub API is \
             source-compatible on day one."
                .to_owned(),
            "3. omp-orchestrator::decide() consumes CycleObservation built FROM \
             producer types; the consumer's private PaneObservation dies."
                .to_owned(),
            "4. The old names become deprecated aliases for one release, then die. \
             Owned by the omp-orchestrator (consumer) side; tracked as follow-up, \
             not silently assumed done."
                .to_owned(),
        ],
    }
}

/// The vocabulary the ecosystem is missing, with exact-name evidence derived
/// from the pinned upstream source. This list IS the deliverable's gap half.
pub fn missing_vocabulary() -> Vec<MissingTypeRow> {
    vec![
        MissingTypeRow {
            name: "Grade".to_owned(),
            status: MissingStatus::AbsentEverywhere,
            evidence: "No crate declares it; no asupersync type of this exact \
                       name exists (derived: grep of src/ at fa3c01aec). The gap \
                       that makes grading prose: six Verdict types, no Grade."
                .to_owned(),
        },
        MissingTypeRow {
            name: "DeliveryClass".to_owned(),
            status: MissingStatus::PresentUpstreamBlocked,
            evidence: "asupersync messaging/class.rs:17 (five variants: \
                       EphemeralInteractive/DurableOrdered/ObligationBacked/\
                       MobilitySafe/ForensicReplayable) behind \
                       #[cfg(feature = \"messaging-fabric\")] \
                       (messaging/mod.rs:78-79). Without the feature: E0433 \
                       (probe-verified 2026-08-31). With messaging-fabric alone: \
                       E0599, consumer.rs:1299 un-gated fn default() calls \
                       TaskId::new_ephemeral() which is \
                       cfg(any(test, feature = \"test-internals\")) (orchestrator \
                       measurement 2026-08-31); +test-internals compiles but \
                       reintroduces the leak upstream issue #46 closed. BLOCKED \
                       at pin fa3c01aec; unblock = upstream gates that fn or \
                       ships a fixed rev."
                .to_owned(),
        },
        MissingTypeRow {
            name: "AckKind".to_owned(),
            status: MissingStatus::PresentUpstreamBlocked,
            evidence: "TWO upstream declarations (derived): UNINHABITED marker \
                       `pub enum AckKind {}` obligation/graded.rs:790 — the one \
                       omp-types re-exported by name in its first draft (scar); \
                       inhabited five-variant messaging/class.rs:83, behind the \
                       same BLOCKED messaging-fabric feature gate as \
                       DeliveryClass. Same evidence and unblock path."
                .to_owned(),
        },
        MissingTypeRow {
            name: "ObligationLedger".to_owned(),
            status: MissingStatus::AbsentEverywhere,
            evidence: "Exact name absent BOTH sides (derived: grep of asupersync \
                       src/ at fa3c01aec and of crates/). Nearest upstream: \
                       CrdtObligationLedger obligation/crdt.rs:219 and \
                       LedgerSnapshot crdt.rs:507 — CRDT obligation entries, not \
                       the reserve/commit/abort ledger the bead describes. Do not \
                       map this row onto the CRDT types without a semantics \
                       decision."
                .to_owned(),
        },
        MissingTypeRow {
            name: "Budget".to_owned(),
            status: MissingStatus::PresentUpstreamUsable,
            evidence: "CORRECTION to the bead's 'ABSENT': asupersync \
                       types/budget.rs:173 `pub struct Budget { deadline, \
                       poll_quota, cost_quota, priority }`, and asupersync::types \
                       COMPILES at our pin (cargo check -p omp-types, \
                       verified 2026-08-31). Reachable today via omp-types \
                       re-export. Adoption is a separate decision; mapping a \
                       surface is not adopting it."
                .to_owned(),
        },
        MissingTypeRow {
            name: "Outcome".to_owned(),
            status: MissingStatus::PresentWrongSemantics,
            evidence: "tick-monitor declares a local Outcome unrelated to \
                       asupersync::types::Outcome<T,E>, whose variants are \
                       Ok/Err/Cancelled(CancelReason)/Panicked \
                       (types/outcome.rs:218, derived — there is no Completed; \
                       scar #2). The local one shadows the upstream name in grep \
                       results and will mislead the next mapper."
                .to_owned(),
        },
    ]
}

/// Find `#[cfg(test)] mod ...` spans so their declarations are tagged
/// `in_test_module` and excluded from collision detection.
fn cfg_test_module_spans(text: &str) -> Vec<(usize, usize)> {
    let mut spans = Vec::new();
    let marker = regex::Regex::new(r"#\[cfg\(test\)\]\s*\n\s*mod\s+\w+[^{]*\{")
        .expect("static regex parses");
    for m in marker.find_iter(text) {
        let start = m.end() - 1; // at '{'
        let mut depth = 0usize;
        for (i, ch) in text[start..].char_indices() {
            match ch {
                '{' => depth += 1,
                '}' => {
                    depth -= 1;
                    if depth == 0 {
                        spans.push((start, start + i));
                        break;
                    }
                }
                _ => {}
            }
        }
    }
    spans
}

fn in_spans(spans: &[(usize, usize)], pos: usize) -> bool {
    spans.iter().any(|(a, b)| *a <= pos && pos <= *b)
}

/// Parse one source file into declarations + type re-exports.
fn parse_source(
    crate_name: &str,
    rel_path: &str,
    text: &str,
    decls: &mut Vec<TypeDecl>,
    reexports: &mut Vec<TypeReexport>,
) {
    let spans = cfg_test_module_spans(text);
    let decl_re =
        regex::Regex::new(r"(?m)^[ \t]*pub\s+(struct|enum)\s+([A-Z][A-Za-z0-9_]*)")
            .expect("static regex parses");
    for m in decl_re.captures_iter(text) {
        let whole = m.get(0).expect("group 0");
        let kind = match &m[1] {
            "struct" => TypeKind::Struct,
            _ => TypeKind::Enum,
        };
        decls.push(TypeDecl {
            crate_name: crate_name.to_owned(),
            name: m[2].to_owned(),
            kind,
            rel_path: rel_path.to_owned(),
            line: text[..whole.start()].lines().count() + 1,
            in_test_module: in_spans(&spans, whole.start()),
        });
    }
    // `pub use path::{A, B, C};` and single `pub use path::Name;`
    let braced =
        regex::Regex::new(r"(?m)^[ \t]*pub\s+use\s+([A-Za-z0-9_:]+)::\{([^}]*)\}\s*;")
            .expect("static regex parses");
    for m in braced.captures_iter(text) {
        let from = m[1].to_owned();
        for name in m[2].split(',') {
            let name = name.trim();
            if name.is_empty() {
                continue;
            }
            reexports.push(TypeReexport {
                crate_name: crate_name.to_owned(),
                name: name.to_owned(),
                from: from.clone(),
            });
        }
    }
    let single =
        regex::Regex::new(r"(?m)^[ \t]*pub\s+use\s+([A-Za-z0-9_]+)::([A-Z][A-Za-z0-9_]*)\s*;")
            .expect("static regex parses");
    for m in single.captures_iter(text) {
        reexports.push(TypeReexport {
            crate_name: crate_name.to_owned(),
            name: m[2].to_owned(),
            from: m[1].to_owned(),
        });
    }
}

/// Walk `crates/*/src/**/*.rs` under `repo_root` and build the inventory.
///
/// Errors (typed, never silent): a missing `crates/` root; a workspace with
/// zero crates; a crate with zero sources.
pub fn scan_workspace_types(repo_root: &Path) -> Result<TypeInventory, crate::InventoryError> {
    let crates_root = repo_root.join("crates");
    if !crates_root.is_dir() {
        return Err(crate::InventoryError::InvalidInput(format!(
            "no crates/ directory under {}",
            repo_root.display()
        )));
    }
    let mut entries: Vec<_> = std::fs::read_dir(&crates_root)
        .map_err(|e| crate::InventoryError::InvalidInput(format!("crates/ unreadable: {e}")))?
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.join("Cargo.toml").is_file())
        .collect();
    entries.sort();
    if entries.is_empty() {
        return Err(crate::InventoryError::InvalidInput(
            "crates/ contains no member crates".to_owned(),
        ));
    }

    let mut inventory_crates = Vec::new();
    for crate_dir in entries {
        let crate_name = crate_dir
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or_default()
            .to_owned();
        let src = crate_dir.join("src");
        let mut decls = Vec::new();
        let mut reexports = Vec::new();
        if src.is_dir() {
            let mut files = walk(src.clone());
            files.sort();
            if files.is_empty() {
                return Err(crate::InventoryError::InvalidInput(format!(
                    "crate {crate_name} has a src/ directory with no .rs files"
                )));
            }
            for f in files {
                let rel = f
                    .strip_prefix(&crate_dir)
                    .unwrap_or(&f)
                    .to_string_lossy()
                    .to_string();
                let text = std::fs::read_to_string(&f).map_err(|e| {
                    crate::InventoryError::InvalidInput(format!("cannot read {rel}: {e}"))
                })?;
                parse_source(&crate_name, &rel, &text, &mut decls, &mut reexports);
            }
        }
        inventory_crates.push(CrateTypes {
            crate_name,
            decls,
            reexports,
        });
    }

    Ok(assemble(inventory_crates))
}

fn walk(dir: std::path::PathBuf) -> Vec<std::path::PathBuf> {
    let mut out = Vec::new();
    let mut stack = vec![dir];
    while let Some(d) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&d) else {
            continue;
        };
        for e in entries.filter_map(|e| e.ok()) {
            let p = e.path();
            if p.is_dir() {
                stack.push(p);
            } else if p.extension().is_some_and(|x| x == "rs") {
                out.push(p);
            }
        }
    }
    out
}

/// Pure assembly: collisions, allowance matching, named zeros, counts, state.
/// Separated from I/O so the gate is testable on synthetic crate sets.
pub fn assemble(crates: Vec<CrateTypes>) -> TypeInventory {
    // name -> crate -> sites (non-test declarations only)
    let mut by_name: BTreeMap<String, BTreeMap<String, Vec<String>>> = BTreeMap::new();
    let mut enums = 0usize;
    let mut structs = 0usize;
    let mut reexport_count = 0usize;
    for c in &crates {
        for d in &c.decls {
            if d.in_test_module {
                continue;
            }
            match d.kind {
                TypeKind::Enum => enums += 1,
                TypeKind::Struct => structs += 1,
            }
            by_name
                .entry(d.name.clone())
                .or_default()
                .entry(c.crate_name.clone())
                .or_default()
                .push(format!("{}/{}:{}", c.crate_name, d.rel_path, d.line));
        }
        reexport_count += c.reexports.len();
    }

    let mut collisions = Vec::new();
    for (name, crate_sites) in by_name {
        if crate_sites.len() < 2 {
            continue;
        }
        let mut keys: Vec<String> = crate_sites.keys().cloned().collect();
        keys.sort();
        let crate_key = keys.join("+");
        let crate_names: Vec<String> = crate_sites.keys().cloned().collect();
        let sites: Vec<String> = crate_sites.into_values().flatten().collect();
        let allowance = ALLOWED_COLLISIONS
            .iter()
            .find(|(n, pair, _)| *n == name && *pair == crate_key)
            .map(|(_, _, reason)| reason.to_string());
        collisions.push(TypeCollision {
            name,
            crates: crate_names,
            sites,
            allowance,
        });
    }

    let mut named_zeros = Vec::new();
    for c in &crates {
        let has_public_decls = c.decls.iter().any(|d| !d.in_test_module);
        if !has_public_decls && c.reexports.is_empty() {
            if let Some((_, reason)) = NAMED_ZEROS.iter().find(|(n, _)| *n == c.crate_name) {
                named_zeros.push(format!("{}: {}", c.crate_name, reason));
            }
        }
    }

    let state = if collisions.iter().any(|c| c.allowance.is_none()) {
        ProbeState::Unknown
    } else {
        ProbeState::Known
    };

    TypeInventory {
        schema_version: "1".to_owned(),
        generated_by: "omp-inventory-map::types_inventory".to_owned(),
        state,
        counts: TypeCounts {
            enums,
            structs,
            reexports: reexport_count,
            crates_scanned: crates.len(),
            crates_with_types: crates
                .iter()
                .filter(|c| c.decls.iter().any(|d| !d.in_test_module) || !c.reexports.is_empty())
                .count(),
        },
        crates,
        collisions,
        missing: missing_vocabulary(),
        seam_decisions: vec![observation_seam_decision()],
        named_zeros,
    }
}

impl TypeInventory {
    /// Every collision that has NO allowance row — each is a gate failure.
    pub fn disallowed(&self) -> Vec<&TypeCollision> {
        self.collisions
            .iter()
            .filter(|c| c.allowance.is_none())
            .collect()
    }

    /// The gate. Errors name both crates per disallowed collision, plus any
    /// structural violation (anti-vacuity, unnamed zero, stale allowance).
    pub fn check(&self) -> Result<(), Vec<String>> {
        let mut errors = Vec::new();

        // Anti-vacuity: an empty scan set is an ERROR, never a pass.
        if self.counts.enums + self.counts.structs == 0 {
            errors.push(
                "anti-vacuity: zero public types discovered across the whole \
                 workspace — the scan set is empty, which is an error, never a \
                 clean inventory"
                    .to_owned(),
            );
        }

        // Disallowed collisions: name both crates.
        for c in self.disallowed() {
            errors.push(format!(
                "COLLISION {} declared by {}: {} — no allowance row carries a \
                 reason (see ALLOWED_COLLISIONS)",
                c.name,
                c.crates.join(" + "),
                c.sites.join(", ")
            ));
        }

        // Unnamed zeros: a crate with no output at all that is not a named
        // zero is a finding, not silence.
        let named: Vec<&str> = NAMED_ZEROS.iter().map(|(n, _)| *n).collect();
        for c in &self.crates {
            let has_decls = c.decls.iter().any(|d| !d.in_test_module);
            if !has_decls && c.reexports.is_empty() && !named.contains(&c.crate_name.as_str()) {
                errors.push(format!(
                    "NAMED-ZERO REQUIRED: crate {} declares no public type and \
                     re-exports none — name the zero with a reason in \
                     NAMED_ZEROS or give it a type",
                    c.crate_name
                ));
            }
        }

        // Stale allowance: a row that no longer corresponds to a real
        // collision is drift and must be pruned. (Validated against the REAL
        // workspace scan; synthetic fixtures skip this via `check_fixture`.)
        if self.crates_scanned_is_real_workspace() {
            for (name, _, _) in ALLOWED_COLLISIONS {
                if !self.collisions.iter().any(|c| &c.name == name) {
                    errors.push(format!(
                        "STALE ALLOWANCE: {name} no longer collides — prune the \
                         row (an allowance for a non-existent duplication is \
                         drift)"
                    ));
                }
            }
        }

        if errors.is_empty() {
            Ok(())
        } else {
            Err(errors)
        }
    }

    fn crates_scanned_is_real_workspace(&self) -> bool {
        self.generated_by == "omp-inventory-map::types_inventory"
            && self.crates.iter().any(|c| c.crate_name == "omp-inventory-map")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn crate_with(name: &str, decls: &[(&str, TypeKind)]) -> CrateTypes {
        CrateTypes {
            crate_name: name.to_owned(),
            decls: decls
                .iter()
                .map(|(n, k)| TypeDecl {
                    crate_name: name.to_owned(),
                    name: n.to_string(),
                    kind: *k,
                    rel_path: "src/lib.rs".to_owned(),
                    line: 1,
                    in_test_module: false,
                })
                .collect(),
            reexports: Vec::new(),
        }
    }

    #[test]
    fn every_allowed_collision_row_carries_a_nonempty_reason() {
        for (name, _, reason) in ALLOWED_COLLISIONS {
            assert!(!name.is_empty(), "allowance row with empty name");
            assert!(!reason.trim().is_empty(), "allowance row {name} has empty reason");
        }
        assert!(
            !ALLOWED_COLLISIONS.is_empty(),
            "allowance table must not be silently empty"
        );
    }

    #[test]
    fn every_named_zero_row_carries_a_nonempty_reason() {
        for (name, reason) in NAMED_ZEROS {
            assert!(!name.is_empty());
            assert!(!reason.trim().is_empty(), "named zero {name} has empty reason");
        }
    }

    #[test]
    fn positive_control_unique_types_pass() {
        let inv = assemble(vec![
            crate_with("alpha", &[("Alpha", TypeKind::Struct), ("AlphaKind", TypeKind::Enum)]),
            crate_with("beta", &[("Beta", TypeKind::Struct)]),
        ]);
        assert!(
            inv.check().is_ok(),
            "crates with unique well-formed types must pass: {:?}",
            inv.check().unwrap_err()
        );
    }

    #[test]
    fn collision_without_allowance_fails_and_names_both_crates() {
        let inv = assemble(vec![
            crate_with("alpha", &[("Finding", TypeKind::Struct)]),
            crate_with("beta", &[("Finding", TypeKind::Struct)]),
        ]);
        let err = inv.check().expect_err("collision must fail the gate");
        assert!(
            err.iter().any(|e| e.contains("alpha") && e.contains("beta")),
            "error must name BOTH crates: {err:?}"
        );
    }

    #[test]
    fn allowed_collision_passes_but_is_visible_in_output() {
        let inv = assemble(vec![
            crate_with("state-wildcard-lint", &[("Finding", TypeKind::Struct)]),
            crate_with("finding", &[("Finding", TypeKind::Struct)]),
        ]);
        inv.check().expect("allowed collision must pass");
        assert_eq!(inv.collisions.len(), 1);
        assert!(inv.collisions[0].allowance.is_some());
    }

    #[test]
    fn test_module_declarations_never_collide() {
        let mut b = crate_with(
            "beta",
            &[("Beta", TypeKind::Struct), ("Finding", TypeKind::Struct)],
        );
        // beta's Finding is inside a cfg(test) module -> not public API;
        // beta keeps a real public type so it is not a named-zero finding.
        b.decls[1].in_test_module = true;
        let inv = assemble(vec![
            crate_with("alpha", &[("Finding", TypeKind::Struct)]),
            b,
        ]);
        assert!(
            inv.check().is_ok(),
            "cfg(test) declarations must not participate in collisions: {:?}",
            inv.check().unwrap_err()
        );
    }

    #[test]
    fn anti_vacuity_zero_types_everywhere_is_an_error() {
        let inv = assemble(vec![crate_with("alpha", &[]), crate_with("beta", &[])]);
        let err = inv.check().expect_err("empty inventory must error");
        assert!(err.iter().any(|e| e.contains("anti-vacuity")), "{err:?}");
    }

    #[test]
    fn unnamed_zero_crate_requires_a_named_row() {
        let inv = assemble(vec![
            crate_with("alpha", &[("Alpha", TypeKind::Struct)]),
            crate_with("mystery", &[]),
        ]);
        let err = inv.check().expect_err("unnamed zero must error");
        assert!(err.iter().any(|e| e.contains("mystery")), "{err:?}");
    }

    #[test]
    fn reexport_only_crate_is_not_a_zero() {
        let c = CrateTypes {
            crate_name: "omp-types".to_owned(),
            decls: Vec::new(),
            reexports: vec![TypeReexport {
                crate_name: "omp-types".to_owned(),
                name: "Outcome".to_owned(),
                from: "asupersync::types".to_owned(),
            }],
        };
        let inv = assemble(vec![crate_with("alpha", &[("Alpha", TypeKind::Struct)]), c]);
        assert!(
            inv.check().is_ok(),
            "reexport-only crate must not be a zero: {:?}",
            inv.check().unwrap_err()
        );
    }

    #[test]
    fn observation_has_a_decision_row_not_an_allowance() {
        assert!(
            !ALLOWED_COLLISIONS.iter().any(|(n, _, _)| *n == "Observation"),
            "Observation must NOT be an allowance row"
        );
        let d = observation_seam_decision();
        assert_eq!(d.type_name, "Observation");
        assert!(d.decision.contains("CONVERGE"));
        assert!(d.shared_home.starts_with("omp-types"));
        assert_eq!(d.migration.len(), 4);
    }

    #[test]
    fn missing_vocabulary_covers_the_six_bead_rows_with_derived_statuses() {
        let want: &[(&str, MissingStatus)] = &[
            ("Grade", MissingStatus::AbsentEverywhere),
            ("DeliveryClass", MissingStatus::PresentUpstreamBlocked),
            ("AckKind", MissingStatus::PresentUpstreamBlocked),
            ("ObligationLedger", MissingStatus::AbsentEverywhere),
            ("Budget", MissingStatus::PresentUpstreamUsable),
            ("Outcome", MissingStatus::PresentWrongSemantics),
        ];
        let rows = missing_vocabulary();
        for (name, status) in want {
            let row = rows
                .iter()
                .find(|r| &r.name == name)
                .unwrap_or_else(|| panic!("missing row {name}"));
            assert_eq!(&row.status, status, "row {name} status drifted");
            assert!(
                row.evidence.len() > 40,
                "row {name} must carry derived evidence, not a stub"
            );
        }
        assert_eq!(rows.len(), 6, "exactly the six bead rows");
    }

    /// MUTATION (acceptance 7), on a synthetic fixture: introduce a deliberate
    /// collision, the gate goes RED naming both crates; restore
    /// byte-identically (sha-verified) and the gate goes green again.
    #[test]
    fn mutation_introduce_collision_then_restore_byte_identically() {
        let dir = std::env::temp_dir().join(format!(
            "omp-inv-mutation-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .expect("clock")
                .as_nanos()
        ));
        let a_src = dir.join("alpha/src");
        let b_src = dir.join("beta/src");
        std::fs::create_dir_all(&a_src).expect("mkdir");
        std::fs::create_dir_all(&b_src).expect("mkdir");
        let a_file = a_src.join("lib.rs");
        let b_file = b_src.join("lib.rs");
        std::fs::write(&a_file, "pub struct Alpha;\n").expect("write a");
        let b_original = b"pub struct Beta;\n".to_vec();
        std::fs::write(&b_file, &b_original).expect("write b");

        let mut before = std::fs::read(&a_file).expect("read a");
        before.extend_from_slice(&std::fs::read(&b_file).expect("read b"));

        // MUTATE: beta now declares Alpha too -> collision
        std::fs::write(&b_file, b"pub struct Alpha;\n").expect("mutate b");

        let inv = assemble(vec![
            parse_fixture(&a_src, "alpha"),
            parse_fixture(&b_src, "beta"),
        ]);
        let err = inv.check().expect_err("deliberate collision must go RED");
        assert!(
            err.iter().any(|e| e.contains("COLLISION Alpha")
                && e.contains("alpha")
                && e.contains("beta")),
            "RED must name the type and BOTH crates: {err:?}"
        );

        // RESTORE byte-identically
        std::fs::write(&b_file, &b_original).expect("restore b");
        let mut after = std::fs::read(&a_file).expect("read a");
        after.extend_from_slice(&std::fs::read(&b_file).expect("read b"));
        assert_eq!(
            sha256_hex(&before),
            sha256_hex(&after),
            "restore must be byte-identical (sha both sides)"
        );

        let inv2 = assemble(vec![
            parse_fixture(&a_src, "alpha"),
            parse_fixture(&b_src, "beta"),
        ]);
        inv2.check().expect("restored fixture must go green");

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// Scan a fixture src dir using the same parse path as the real walker.
    fn parse_fixture(src: &Path, crate_name: &str) -> CrateTypes {
        let mut decls = Vec::new();
        let mut reexports = Vec::new();
        for f in walk(src.to_path_buf()) {
            let text = std::fs::read_to_string(&f).expect("read fixture");
            let rel = format!("src/{}", f.file_name().unwrap().to_string_lossy());
            parse_source(crate_name, &rel, &text, &mut decls, &mut reexports);
        }
        CrateTypes {
            crate_name: crate_name.to_owned(),
            decls,
            reexports,
        }
    }

    fn sha256_hex(bytes: &[u8]) -> String {
        // FNV-1a 64 is enough for byte-identity checking in a fixture test
        // without adding a crypto dependency to a scanner crate.
        let mut h: u64 = 0xcbf29ce484222325;
        for b in bytes {
            h ^= u64::from(*b);
            h = h.wrapping_mul(0x100000001b3);
        }
        format!("{h:016x}")
    }

    /// POSITIVE CONTROL on the REAL workspace: today's four measured
    /// collisions carry their rows (Observation carries the DECISION), the
    /// rest of the fleet is unique, and the inventory discovers real volume.
    #[test]
    fn real_workspace_today_all_collisions_accounted_and_volume_real() {
        let repo = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent())
            .expect("repo root is two levels above the crate");
        let inv = scan_workspace_types(repo).expect("scan works");

        assert!(inv.counts.enums >= 50, "enums floor: {}", inv.counts.enums);
        assert!(inv.counts.structs >= 79, "structs floor: {}", inv.counts.structs);
        assert!(inv.counts.crates_with_types >= 20, "crates-with-types floor");

        let names: Vec<&str> = inv.collisions.iter().map(|c| c.name.as_str()).collect();
        // Pinned to the measured set, re-derived 2026-09-01 after two crates landed.
        //
        // `DispatchIntent` and `GateError` are new since this list was written, and
        // both are already carried with reasons in no-shell-gate's COLLISION_ALLOWANCE
        // — which is the real finding here: **two crates independently pin the same
        // fact.** This assertion and that allowance list must be edited together, and
        // nothing enforces that they agree. A single shared source would remove the
        // class; it does not exist yet, so this comment is the only link between them.
        assert_eq!(
            names,
            vec![
                "DispatchIntent",
                "Finding",
                "GateError",
                "LintReport",
                "Observation",
                "Violation",
            ],
            "today's measured collision set (sorted)"
        );

        let obs = inv
            .collisions
            .iter()
            .find(|c| c.name == "Observation")
            .expect("Observation collision present");
        assert!(obs.allowance.is_none(), "Observation must not be allowed");
        assert_eq!(inv.seam_decisions.len(), 1);
        assert_eq!(inv.seam_decisions[0].type_name, "Observation");
        for c in &inv.collisions {
            if c.name != "Observation" {
                assert!(c.allowance.is_some(), "{} must carry its allowance", c.name);
            }
        }

        // Named zeros: finding-dispatch and pane-dispatch-fence ONLY.
        // omp-types is reexport-only — it is NOT a zero; its provision is
        // asserted separately below via non-empty reexports.
        let zero_names: Vec<&str> = inv
            .named_zeros
            .iter()
            .map(|s| s.split(':').next().expect("prefix"))
            .collect();
        assert_eq!(zero_names, vec!["finding-dispatch", "pane-dispatch-fence"]);
        let omp_types = inv
            .crates
            .iter()
            .find(|c| c.crate_name == "omp-types")
            .expect("omp-types present");
        assert!(
            !omp_types.reexports.is_empty(),
            "omp-types is a vocabulary crate: reexports must be non-empty"
        );

        let verdicts: Vec<&str> = inv
            .crates
            .iter()
            .flat_map(|c| c.decls.iter())
            .filter(|d| !d.in_test_module && d.name.contains("Verdict"))
            .map(|d| d.name.as_str())
            .collect();
        assert_eq!(verdicts.len(), 13, "thirteen Verdict types measured: {verdicts:?}");

        // The four rows the gate enforces beyond collisions.
        let errs = inv.check().expect_err(
            "Observation collision is REFUSED until the seam convergence lands",
        );
        assert!(
            errs.iter().any(|e| e.contains("COLLISION Observation")),
            "the gate must name the refused seam: {errs:?}"
        );
    }
}
